---
- hosts: all
  become: yes
  pre_tasks:
    - name: "install etckeeper"
      apt: name=etckeeper
  roles:
    - znzj.ja_jp
    - packages
    - znz.journald
    - znz.timesyncd
    - znz.nadoka-private
  vars_files:
    - config.yml
- hosts: all
  become: no
  roles:
    - znz.user-dot-shell
    - user-anyenv
    - user-go
    - user-libressl
    - user-ruby-git
    - user-old-openssl
    - user-vim
  vars_files:
    - user-config.yml
