---
- hosts: all
  become: yes
  pre_tasks:
    - name: "install etckeeper"
      apt: name=etckeeper
  roles:
    - znzj.ja_jp
    - packages
    - journald
    - timesyncd
    - nadoka
  vars_files:
    - config.yml
- hosts: all
  become: no
  roles:
    - user-dot-shell
    - user-anyenv
    - user-go
  vars_files:
    - user-config.yml
