- src: znzj.ja_jp
- src: znz.journald
- src: znz.timesyncd
- src: https://github.com/znz/ansible-role-nadoka-private
  version: master
  name: znz.nadoka-private
- src: https://github.com/znz/ansible-role-user-dot-shell
  version: master
  name: znz.user-dot-shell
- src: https://github.com/znz/ansible-role-user-anyenv
  version: master
  name: znz.user-anyenv
- src: https://github.com/znz/ansible-role-user-tools
  version: master
  name: znz.user-tools
- src: https://github.com/znz/ansible-role-user-libressl
  version: master
  name: znz.user-libressl
- src: https://github.com/znz/ansible-role-user-ruby-git
  version: master
  name: znz.user-ruby-git
- src: https://github.com/znz/ansible-role-user-old-openssl
  version: master
  name: znz.user-old-openssl
