---
- name: "$HOME/bin"
  file:
    state: directory
    path: "/home/{{ user }}/bin"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
- name: "{{ go_download_dir }}"
  file:
    state: directory
    path: "{{ go_download_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
- name: "{{ go_download_dir }}/ghq"
  file:
    state: directory
    path: "{{ go_download_dir }}/ghq"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
- name: "download ghq"
  get_url:
    url: https://github.com/motemen/ghq/releases/download/v0.7.4/ghq_linux_amd64.zip
    dest: "{{ go_download_dir }}/ghq_linux_amd64.zip"
    checksum: sha1:e471825c1e8eb3a1162bf306bd1eb12ddb232a00
- name: "extract ghq"
  unarchive:
    src: "{{ go_download_dir }}/ghq_linux_amd64.zip"
    dest: "{{ go_download_dir }}/ghq"
    remote_src: yes
    creates: "{{ go_download_dir }}/ghq/ghq"
- name: "bin/ghq"
  file:
    state: link
    force: yes
    src: "{{ go_download_dir }}/ghq/ghq"
    dest: "/home/{{ user }}/bin/ghq"
    owner: "{{ user }}"
    group: "{{ group }}"
- name: "download peco"
  get_url:
    url: https://github.com/peco/peco/releases/download/v0.4.7/peco_linux_amd64.tar.gz
    dest: "{{ go_download_dir }}/peco_linux_amd64.tar.gz"
    checksum: sha1:89436cbb65d9423d029ac9c0ebc6d409e2483212
- name: "extract peco"
  unarchive:
    src: "{{ go_download_dir }}/peco_linux_amd64.tar.gz"
    dest: "{{ go_download_dir }}"
    remote_src: yes
- name: "bin/peco"
  file:
    state: link
    force: yes
    src: "{{ go_download_dir }}/peco_linux_amd64/peco"
    dest: "/home/{{ user }}/bin/peco"
    owner: "{{ user }}"
    group: "{{ group }}"
