---
- name: install runit
  apt:
    name: runit
    install_recommends: no
- name: install runit-systemd
  apt: name=runit-systemd
  when: ansible_distribution_release == 'yakkety'
- name: install git and subversion
  apt:
    name:
      - git
      - subversion
- name: "log/run"
  copy:
    src: "log-run.sh"
    dest: "/etc/sv/log-run"
    owner: root
    group: root
    mode: 0755
- name: "directories in /etc/sv"
  file:
    state: directory
    path: "/etc/sv/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'nadoka-fprog'
    - 'nadoka-fprog/log'
    - 'nadoka-slack'
    - 'nadoka-slack/log'
- name: "log/run in /etc/sv"
  file:
    state: link
    force: yes
    src: "../../log-run"
    dest: "/etc/sv/{{ item }}/log/run"
    owner: root
    group: root
  with_items:
    - 'nadoka-fprog'
    - 'nadoka-slack'
- name: "supervise in /etc/sv"
  file:
    state: link
    force: yes
    src: "/var/run/{{ item.src }}"
    dest: "/etc/sv/{{ item.dest }}/supervise"
    owner: root
    group: root
  with_items:
    - { src: 'sv.nadoka-fprog', dest: 'nadoka-fprog' }
    - { src: 'sv.nadoka-fprog.log', dest: 'nadoka-fprog/log' }
    - { src: 'sv.nadoka-slack', dest: 'nadoka-slack' }
    - { src: 'sv.nadoka-slack.log', dest: 'nadoka-slack/log' }
- name: "run in /etc/sv"
  template:
    src: "run.j2"
    dest: "/etc/sv/{{ item }}/run"
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'nadoka-fprog'
    - 'nadoka-slack'
- name: "run-item in /etc/sv"
  template:
    src: "run-item.j2"
    dest: "/etc/sv/{{ item }}/run-{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'nadoka-fprog'
    - 'nadoka-slack'

- name: "nadoka-fprog.rc"
  copy:
    src: "nadoka-fprog.rc"
    dest: "/etc/sv/nadoka-fprog/nadoka-fprog.rc"
    owner: root
    group: root
    mode: 0755
- name: "nadoka-fprog host"
  copy:
    content: "{{ nadoka_fprog_host }}"
    dest: "/etc/sv/nadoka-fprog/host"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-fprog port"
  copy:
    content: "{{ nadoka_fprog_port }}"
    dest: "/etc/sv/nadoka-fprog/port"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-fprog pass"
  copy:
    content: "{{ nadoka_fprog_pass }}"
    dest: "/etc/sv/nadoka-fprog/pass"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-fprog key"
  copy:
    content: "{{ nadoka_fprog_key }}"
    dest: "/etc/sv/nadoka-fprog/key"
    owner: root
    group: "{{ group }}"
    mode: 0640

- name: "nadoka-slack.rc"
  copy:
    src: "nadoka-slack.rc"
    dest: "/etc/sv/nadoka-slack/nadoka-slack.rc"
    owner: root
    group: root
    mode: 0755
- name: "nadoka-slack host"
  copy:
    content: "{{ nadoka_slack_host }}"
    dest: "/etc/sv/nadoka-slack/host"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-slack port"
  copy:
    content: "{{ nadoka_slack_port }}"
    dest: "/etc/sv/nadoka-slack/port"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-slack pass"
  copy:
    content: "{{ nadoka_slack_pass }}"
    dest: "/etc/sv/nadoka-slack/pass"
    owner: root
    group: "{{ group }}"
    mode: 0640
- name: "nadoka-slack key"
  copy:
    content: "{{ nadoka_slack_user }}"
    dest: "/etc/sv/nadoka-slack/user"
    owner: root
    group: "{{ group }}"
    mode: 0640

- name: enable nadoka
  file:
    state: link
    src: "/etc/sv/{{ item }}"
    dest: "/etc/service/{{ item }}"
    owner: root
    group: root
  with_items:
    - 'nadoka-fprog'
    - 'nadoka-slack'
